"""Generic linear-probe fitting and evaluation."""

from analysis.probes.factorization import (
    CorrelationResidualProbe,
    ProductConstrainedJointProbe,
    center_within_groups,
    correlation_residual,
    correlation_residual_metrics,
    dimension_additivity,
    effective_dimension,
    fit_correlation_residual_probe,
    fit_product_constrained_joint_probe,
    joint_readout_excess_subspace,
    orthonormal_basis,
    pairwise_subspace_overlaps,
    principal_component_basis,
    readout_subspace,
    regression_factor_geometry,
    regression_factor_subspaces,
    representation_dimension_predictions,
    rowwise_tensor_product,
    subspace_overlap,
    product_constrained_joint_metrics,
    variance_geometry,
    vary_one_subspace,
)
from analysis.probes.linear import (
    conditional_mse_metrics,
    conditional_residual_r2,
    fit_affine_probe,
    global_mse_metrics,
    mean_squared_error,
    probe_predict,
    r2_score,
    split_group_indices,
    split_indices,
    target_variance,
)
from analysis.probes.resampling import (
    cluster_bootstrap_statistics,
    held_out_permutation_null,
    percentile_interval,
)
from analysis.probes.transducer import (
    predictive_belief_sequence,
    predictive_belief_update,
)

__all__ = [
    "CorrelationResidualProbe",
    "ProductConstrainedJointProbe",
    "center_within_groups",
    "correlation_residual",
    "correlation_residual_metrics",
    "conditional_mse_metrics",
    "conditional_residual_r2",
    "cluster_bootstrap_statistics",
    "dimension_additivity",
    "effective_dimension",
    "fit_correlation_residual_probe",
    "fit_affine_probe",
    "fit_product_constrained_joint_probe",
    "global_mse_metrics",
    "held_out_permutation_null",
    "joint_readout_excess_subspace",
    "mean_squared_error",
    "orthonormal_basis",
    "pairwise_subspace_overlaps",
    "percentile_interval",
    "principal_component_basis",
    "predictive_belief_sequence",
    "predictive_belief_update",
    "probe_predict",
    "product_constrained_joint_metrics",
    "readout_subspace",
    "regression_factor_geometry",
    "regression_factor_subspaces",
    "representation_dimension_predictions",
    "rowwise_tensor_product",
    "r2_score",
    "split_group_indices",
    "split_indices",
    "subspace_overlap",
    "target_variance",
    "variance_geometry",
    "vary_one_subspace",
]
